project:
  type: website

website:
  title: "DanMazJen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      #- text: Projects.qmd
      #  href: project.qmd
      - text: Blog
        href: blog/index.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css
    toc: true

# editor: visual

resources: 
 - apps/**
