<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daniel S. Mazhari-Jensen">
<meta name="dcterms.date" content="2025-07-23">
<meta name="description" content="Using lme4, I show why random slopes is often needed in biomedical research and experiments">

<title>Why random slopes matters… – DanMazJen.github.io</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">DanMazJen.github.io</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#multi-level-models-and-why-random-slopes-matter" id="toc-multi-level-models-and-why-random-slopes-matter" class="nav-link active" data-scroll-target="#multi-level-models-and-why-random-slopes-matter">Multi-level models and why random slopes matter</a>
  <ul class="collapse">
  <li><a href="#how-two-memes-helped-me-learn-something-about-mixed-effect-models" id="toc-how-two-memes-helped-me-learn-something-about-mixed-effect-models" class="nav-link" data-scroll-target="#how-two-memes-helped-me-learn-something-about-mixed-effect-models">How two memes helped me learn something about mixed-effect models</a></li>
  <li><a href="#how-well-approach-it" id="toc-how-well-approach-it" class="nav-link" data-scroll-target="#how-well-approach-it">How we’ll approach it:</a></li>
  <li><a href="#simulating-our-data-set" id="toc-simulating-our-data-set" class="nav-link" data-scroll-target="#simulating-our-data-set">Simulating our data set:</a></li>
  <li><a href="#a-brief-look-at-the-data" id="toc-a-brief-look-at-the-data" class="nav-link" data-scroll-target="#a-brief-look-at-the-data">A brief look at the data:</a></li>
  <li><a href="#the-anova-approach-full-pooling" id="toc-the-anova-approach-full-pooling" class="nav-link" data-scroll-target="#the-anova-approach-full-pooling">The ANOVA approach (full pooling)</a>
  <ul class="collapse">
  <li><a href="#what-happens-when-we-ignore-subjects-altogether" id="toc-what-happens-when-we-ignore-subjects-altogether" class="nav-link" data-scroll-target="#what-happens-when-we-ignore-subjects-altogether">What happens when we ignore subjects altogether?</a></li>
  </ul></li>
  <li><a href="#modeling-variation-by-treating-every-participant-as-their-own-experiment-no-pooling" id="toc-modeling-variation-by-treating-every-participant-as-their-own-experiment-no-pooling" class="nav-link" data-scroll-target="#modeling-variation-by-treating-every-participant-as-their-own-experiment-no-pooling">Modeling variation by treating every participant as their own experiment (no pooling)</a></li>
  <li><a href="#multilevel-regression-partial-pooling" id="toc-multilevel-regression-partial-pooling" class="nav-link" data-scroll-target="#multilevel-regression-partial-pooling">Multi’level regression (partial pooling)</a></li>
  <li><a href="#limitations-of-random-intercept-models-in-clinical-inference" id="toc-limitations-of-random-intercept-models-in-clinical-inference" class="nav-link" data-scroll-target="#limitations-of-random-intercept-models-in-clinical-inference">Limitations of Random Intercept Models in Clinical Inference</a></li>
  <li><a href="#random-slopes" id="toc-random-slopes" class="nav-link" data-scroll-target="#random-slopes">Random slopes:</a></li>
  <li><a href="#comparing-models-do-random-slopes-improve-fit" id="toc-comparing-models-do-random-slopes-improve-fit" class="nav-link" data-scroll-target="#comparing-models-do-random-slopes-improve-fit">Comparing models: Do random slopes improve fit?</a></li>
  <li><a href="#interpreting-the-random-effects" id="toc-interpreting-the-random-effects" class="nav-link" data-scroll-target="#interpreting-the-random-effects">Interpreting the Random Effects</a></li>
  <li><a href="#take-away-message" id="toc-take-away-message" class="nav-link" data-scroll-target="#take-away-message">Take-away message:</a></li>
  <li><a href="#old" id="toc-old" class="nav-link" data-scroll-target="#old">old</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section">??</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Why random slopes matters…</h1>
<p class="subtitle lead">… and why random intercepts are often not enough</p>
  <div class="quarto-categories">
    <div class="quarto-category">R</div>
    <div class="quarto-category">lme4</div>
    <div class="quarto-category">multilevel regression</div>
  </div>
  </div>

<div>
  <div class="description">
    Using lme4, I show why random slopes is often needed in biomedical research and experiments
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Daniel S. Mazhari-Jensen </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 23, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="multi-level-models-and-why-random-slopes-matter" class="level1">
<h1>Multi-level models and why random slopes matter</h1>
<section id="how-two-memes-helped-me-learn-something-about-mixed-effect-models" class="level2">
<h2 class="anchored" data-anchor-id="how-two-memes-helped-me-learn-something-about-mixed-effect-models">How two memes helped me learn something about mixed-effect models</h2>
<p>About six months ago, I came across these two memes:</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="plots/random_intercept_only.jpg" class="preview-image img-fluid figure-img"></p>
<figcaption>Meme 1</figcaption>
</figure>
</div>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="plots/what_about_random_slopes.jpg" class="preview-image img-fluid figure-img"></p>
<figcaption>Meme 2</figcaption>
</figure>
</div>
</div>
</div>
<p>At first, I was genuinely puzzled. What exactly is the connection between adding a <strong>random intercept</strong> in a regression model and inflating <strong>Type I error</strong> when you don’t include a <strong>random slope</strong>?</p>
<p>If you, like I did, got intrigued by these meme’s nuggets of information, consider reading along.</p>
<p>My goal here is to unpack what’s going on in a way that’s accessible, honest, and hopefully a little enjoyable. I’m not writing a textbook chapter; this is more of a <em>personal explanation</em> of a concept I found tricky and later came to appreciate.</p>
<p>⚠️ <strong>Note</strong>: I assume you have a basic understanding of regression models and null-significance-hypothesis-tests. What follows is not a deep statistical dive, but it should give you just enough to understand the meme, avoid a common pitfall, and get curious about mixed-effects models. The material is based on:</p>
<ul>
<li>Gelman &amp; Hill</li>
<li>Barr</li>
<li>?</li>
</ul>
</section>
<section id="how-well-approach-it" class="level2">
<h2 class="anchored" data-anchor-id="how-well-approach-it">How we’ll approach it:</h2>
<p>We’ll focus on why <strong>random slopes</strong> are crucial in many types of data—especially in <strong>biometric</strong> or <strong>health science research</strong>, where repeated measures designs are common. We’ll use a small simulation in R to illustrate the key concepts, relying on the <code>lme4</code> package and some <code>tidyverse</code>-style data wrangling.</p>
<p>The data set we’ll use to demonstrate this comes from a simple simulation that mimics a common experimental design: repeated measures of a response variable (here: reaction time) across multiple sessions per participant.</p>
<p>Imagine we are testing whether people improve (get faster) with repeated practice. This is a typical setup in cognitive psychology. Often, researchers want to know: <em>is there a significant learning effect over time?</em></p>
<p>We might want to investigate whether a test we’re performing has an undesirable shift across multiple repeated measures (stability of test instrument) in order to validate it and show it’s feasibility as a repeated measure for a clinical trial, for example for a medical assessment for driving skills under the influence of a given drug.</p>
<p>But here’s the issue (<strong>SPOILER ALLERT!</strong>): if you don’t model the data closely, you might get fundamentally different results!</p>
<p>Let’s dive in and see why.</p>
</section>
<section id="simulating-our-data-set" class="level2">
<h2 class="anchored" data-anchor-id="simulating-our-data-set">Simulating our data set:</h2>
<p>We simulate a data set where each subject completes five sessions of a task. There’s a general trend toward faster responses over time, but with subject-specific differences in both starting reaction time and learning rate.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">314</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>n_subjects <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>n_sessions <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fixed effect of session: general learning effect</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>beta_0 <span class="ot">&lt;-</span> <span class="dv">600</span>   <span class="co"># Average baseline RT in ms</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>beta_1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10</span>   <span class="co"># Average decrease in RT per session</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Random effects: standard deviations</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>sd_intercept <span class="ot">&lt;-</span> <span class="dv">50</span>    <span class="co"># SD of baseline RTs across subjects</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>sd_slope     <span class="ot">&lt;-</span> <span class="dv">25</span>    <span class="co"># SD of learning rates (slopes)</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>rho          <span class="ot">&lt;-</span> <span class="fl">0.2</span>   <span class="co"># Correlation between intercepts and slopes</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Within-subject residual error</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>sigma_error <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct subject-level random effects (correlated)</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>subject_re <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n_subjects,</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sigma =</span> <span class="fu">matrix</span>(<span class="fu">c</span>(sd_intercept<span class="sc">^</span><span class="dv">2</span>, rho<span class="sc">*</span>sd_intercept<span class="sc">*</span>sd_slope,</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>                   rho<span class="sc">*</span>sd_intercept<span class="sc">*</span>sd_slope, sd_slope<span class="sc">^</span><span class="dv">2</span>), <span class="dv">2</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">|&gt;</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="st">"intercept_re"</span>, <span class="st">"slope_re"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">subject =</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span>n_subjects))</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Create session vector repeated for each subject</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>session <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span><span class="sc">:</span>(n_sessions <span class="sc">-</span> <span class="dv">1</span>), <span class="at">times =</span> n_subjects)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Repeat subject IDs for each session</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>subject <span class="ot">&lt;-</span> <span class="fu">rep</span>(subject_re<span class="sc">$</span>subject, <span class="at">each =</span> n_sessions)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Join the random effects</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(<span class="at">subject =</span> subject, <span class="at">session =</span> session) <span class="sc">|&gt;</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">left_join</span>(subject_re, <span class="at">by =</span> <span class="st">"subject"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    <span class="at">reaction_time =</span> beta_0 <span class="sc">+</span> intercept_re <span class="sc">+</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>                    (beta_1 <span class="sc">+</span> slope_re) <span class="sc">*</span> session <span class="sc">+</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">rnorm</span>(dplyr<span class="sc">::</span><span class="fu">n</span>(), <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> sigma_error)</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Here’s the distribution of slopes (ie. learning rate variability):</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>subject_re <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> slope_re)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">fill =</span> <span class="st">"#6495ED"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of subject-specific learning rates (slopes)"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Subject slope (ms per session)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2025-08-22-effect-of-RIonly_RIRS_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="a-brief-look-at-the-data" class="level2">
<h2 class="anchored" data-anchor-id="a-brief-look-at-the-data">A brief look at the data:</h2>
<p>Here’s the structure of our data set:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">glimpse</span>(sim_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150
Columns: 5
$ subject       &lt;fct&gt; 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4,…
$ session       &lt;int&gt; 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3,…
$ intercept_re  &lt;dbl&gt; 63.50593, 63.50593, 63.50593, 63.50593, 63.50593, -38.98…
$ slope_re      &lt;dbl&gt; 14.352662, 14.352662, 14.352662, 14.352662, 14.352662, 1…
$ reaction_time &lt;dbl&gt; 662.9042, 703.3984, 672.8058, 690.5320, 659.7003, 565.97…</code></pre>
</div>
</div>
<p>And each participants’ responses:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>sim_data <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span>reaction_time, <span class="at">x=</span>session)) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> subject, <span class="at">ncol=</span><span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>),<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">4</span>)) <span class="sc">+</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Session"</span>, <span class="at">y =</span> <span class="st">"Reaction Time (ms)"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">title =</span> <span class="st">"Individual learning trajectories across sessions"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2025-08-22-effect-of-RIonly_RIRS_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Generally, our sample shows the following trend at the group-level:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>sim_data <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(session, reaction_time)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> <span class="st">'y ~ x'</span>, <span class="at">color =</span> <span class="st">"firebrick"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Pooled average trend across all subjects"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Session"</span>, <span class="at">y =</span> <span class="st">"Reaction Time (ms)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2025-08-22-effect-of-RIonly_RIRS_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-anova-approach-full-pooling" class="level2">
<h2 class="anchored" data-anchor-id="the-anova-approach-full-pooling">The ANOVA approach (full pooling)</h2>
<section id="what-happens-when-we-ignore-subjects-altogether" class="level3">
<h3 class="anchored" data-anchor-id="what-happens-when-we-ignore-subjects-altogether">What happens when we ignore subjects altogether?</h3>
<p>Before diving into mixed models, let’s start with a simple linear model — the kind you’d use in a basic ANOVA-style analysis. This model assumes complete pooling, meaning all subjects are treated as coming from the same population with no individual differences.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>anova_approach <span class="ot">&lt;-</span> <span class="fu">lm</span>(reaction_time <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> session, sim_data)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_approach)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = reaction_time ~ 1 + session, data = sim_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-230.76  -53.64   -3.20   52.50  341.12 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  614.455     12.161  50.525   &lt;2e-16 ***
session       -7.529      4.965  -1.516    0.132    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 85.99 on 148 degrees of freedom
Multiple R-squared:  0.0153,    Adjusted R-squared:  0.008646 
F-statistic: 2.299 on 1 and 148 DF,  p-value: 0.1316</code></pre>
</div>
</div>
<p>This model estimates a single intercept (baseline reaction time) and a single slope (learning rate) for everyone. It completely ignores the fact that each participant provides multiple data points.</p>
<p>…Here is the model prediction - notice how every participant is assumed to have the same initial value and linear trajectory. This is due to pooling, an assumption from ANOVA. …</p>
<p>Let’s overlay the model predictions onto each subject’s data:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sim_data <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(session, reaction_time, <span class="at">group=</span>subject)) <span class="sc">+</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>subject, <span class="at">ncol=</span><span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span><span class="fu">fitted</span>(anova_approach)), <span class="at">linetype=</span><span class="dv">2</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>),<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2025-08-22-effect-of-RIonly_RIRS_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As you can see, the red dashed line is identical across all panels. That’s because the model assumes all participants behave the same — same starting point, same rate of learning. It completely ignores the fact that participants vary in their baseline speed and how much they improve. This is the statistical assumption behind traditional ANOVA: everyone is treated as identical except for random noise.</p>
<p><em>The elusive discussion of responders/non-responders</em> At first glance, you might look at this and say:</p>
<p>“Ah, some people are improving, others aren’t — we have responders and non-responders!”</p>
<p>But that interpretation would be misleading here. This model can’t tell you who is improving — it just imposes the same trend on everyone. The differences you see are purely residuals (errors), not modeled variation.</p>
</section>
</section>
<section id="modeling-variation-by-treating-every-participant-as-their-own-experiment-no-pooling" class="level2">
<h2 class="anchored" data-anchor-id="modeling-variation-by-treating-every-participant-as-their-own-experiment-no-pooling">Modeling variation by treating every participant as their own experiment (no pooling)</h2>
<p>Modeling each participant separately (no pooling)</p>
<p>To better capture individual differences, we can treat each participant as their own mini-experiment. This means fitting a separate linear regression model for each subject, without assuming any shared parameters. This is the no pooling approach — the opposite extreme of the ANOVA model.</p>
<p>… If we want to be more sensitive to individual variability, we need to allow participants to be modeled more individually. This can be done by computing linear regression for each participant, treating them as individual cases with no overlap. …</p>
<p>There is this need function in lme4 that does this for you:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>no_pooling <span class="ot">&lt;-</span> lme4<span class="sc">::</span><span class="fu">lmList</span>(reaction_time <span class="sc">~</span> session <span class="sc">|</span> subject, sim_data)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(no_pooling)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
  Model: reaction_time ~ session | NULL 
   Data: sim_data 

Coefficients:
   (Intercept) 
   Estimate Std. Error  t value     Pr(&gt;|t|)
1  681.7230   20.83618 32.71823 9.395527e-52
2  577.6282   20.83618 27.72237 7.396652e-46
3  632.6230   20.83618 30.36175 4.511656e-49
4  679.6080   20.83618 32.61672 1.216269e-51
5  578.4442   20.83618 27.76153 6.600455e-46
6  598.0607   20.83618 28.70299 4.435086e-47
7  616.0432   20.83618 29.56603 3.970179e-48
8  607.6337   20.83618 29.16243 1.218478e-47
9  581.2502   20.83618 27.89620 4.465845e-46
10 652.8119   20.83618 31.33069 3.399765e-50
11 566.5336   20.83618 27.18989 3.524528e-45
12 564.4954   20.83618 27.09208 4.707596e-45
13 715.1396   20.83618 34.32201 1.736935e-53
14 630.0177   20.83618 30.23671 6.329860e-49
15 662.4253   20.83618 31.79207 1.015997e-50
16 665.1181   20.83618 31.92130 7.262779e-51
17 708.8651   20.83618 34.02087 3.629525e-53
18 615.6480   20.83618 29.54707 4.183817e-48
19 495.4300   20.83618 23.77739 1.426033e-40
20 613.2376   20.83618 29.43138 5.763393e-48
21 643.3719   20.83618 30.87763 1.129423e-49
22 605.7133   20.83618 29.07026 1.576892e-47
23 583.3266   20.83618 27.99585 3.347891e-46
24 594.4219   20.83618 28.52835 7.279131e-47
25 661.4904   20.83618 31.74720 1.141889e-50
26 536.7667   20.83618 25.76128 2.624430e-43
27 585.9676   20.83618 28.12260 2.323417e-46
28 622.5018   20.83618 29.87600 1.692176e-48
29 551.4993   20.83618 26.46835 3.039224e-44
30 605.8404   20.83618 29.07637 1.550161e-47
   session 
       Estimate Std. Error      t value     Pr(&gt;|t|)
1   -1.92741626   8.506335 -0.226585971 8.212595e-01
2    8.42613664   8.506335  0.990571880 3.245504e-01
3   17.15000676   8.506335  2.016145140 4.676631e-02
4  -19.48394859   8.506335 -2.290522028 2.432725e-02
5   15.05841164   8.506335  1.770258395 8.007041e-02
6   52.82327204   8.506335  6.209874124 1.604886e-08
7  -28.98344395   8.506335 -3.407277354 9.828407e-04
8  -27.01429459   8.506335 -3.175785264 2.046924e-03
9  -27.21776736   8.506335 -3.199705408 1.900477e-03
10  63.03441859   8.506335  7.410290764 6.577572e-11
11   0.98436378   8.506335  0.115721252 9.081313e-01
12 -32.17990897   8.506335 -3.783051982 2.786396e-04
13   6.33994882   8.506335  0.745320814 4.580199e-01
14 -40.56637674   8.506335 -4.768960413 7.097137e-06
15   0.67470483   8.506335  0.079317920 9.369559e-01
16 -17.78312994   8.506335 -2.090574745 3.938578e-02
17  -0.29796817   8.506335 -0.035028971 9.721342e-01
18 -40.63502607   8.506335 -4.777030789 6.873853e-06
19 -34.88493879   8.506335 -4.101053765 9.003999e-05
20  -8.77430658   8.506335 -1.031502542 3.050692e-01
21  -8.86818963   8.506335 -1.042539381 2.999540e-01
22 -14.64719423   8.506335 -1.721915908 8.852003e-02
23 -34.43488446   8.506335 -4.048145632 1.090719e-04
24 -28.50260901   8.506335 -3.350750670 1.179326e-03
25 -10.96645889   8.506335 -1.289210734 2.006284e-01
26  23.05147176   8.506335  2.709918043 8.057916e-03
27  -0.07360777   8.506335 -0.008653288 9.931149e-01
28 -29.04004938   8.506335 -3.413931857 9.618532e-04
29 -17.03479502   8.506335 -2.002600913 4.822955e-02
30   9.91250594   8.506335  1.165308618 2.469733e-01

Residual standard error: 26.89939 on 90 degrees of freedom</code></pre>
</div>
</div>
<p>Now, the model fits the data as follows:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sim_data <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(session, reaction_time, <span class="at">group=</span>subject)) <span class="sc">+</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>subject, <span class="at">ncol=</span><span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span> </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">fitted</span>(no_pooling)), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"No pooling: Separate regression for each subject"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Each subject gets their own intercept and slope"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Days of sleep deprivation"</span>, <span class="at">y =</span> <span class="st">"Reaction time (ms)"</span>) <span class="sc">+</span> </span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>),<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2025-08-22-effect-of-RIonly_RIRS_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>What does this show?</strong> Now, each subject has their own line, fitted independently from the others.</p>
<p>This approach fully respects subject-level variation — but at a cost.</p>
<p>Although no pooling gives us maximum flexibility, it also comes with trade-offs:</p>
<ul>
<li>It doesn’t borrow strength across subjects. If someone has noisy data, their slope might be wildly off.</li>
<li>There’s no generalization — you can’t talk about an average effect across subjects, only 30 separate stories.</li>
<li>In small datasets (as is common in biomedical studies), this often leads to unstable estimates.</li>
</ul>
<p><strong>Key point</strong> No pooling shows us the raw heterogeneity in slopes and intercepts — but it doesn’t help us make population-level inferences or control for noise. We need something in between.</p>
<p>What if we want to both model individual differences and estimate a general trend across subjects?</p>
</section>
<section id="multilevel-regression-partial-pooling" class="level2">
<h2 class="anchored" data-anchor-id="multilevel-regression-partial-pooling">Multi’level regression (partial pooling)</h2>
<p>This is where things get interesting — we’re now ready to bridge the gap between the overly simplistic (ANOVA) and the overly fragmented (no pooling) approaches.</p>
<p><em>Partial pooling with random intercepts</em> The random intercept model is the first step toward balancing the extremes of full pooling and no pooling.</p>
<p>We acknowledge that subjects vary in their baseline levels (reaction times), but we still assume they share a common trend — in this case, how their reaction times change over sessions.</p>
<p>The following code chunk and plot is based on a mixed-effects model: it includes both fixed effects (shared across all subjects) and random effects (varying by subject).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>RI_only <span class="ot">&lt;-</span> lme4<span class="sc">::</span><span class="fu">lmer</span>(reaction_time <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> session <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject), sim_data)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(RI_only)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: reaction_time ~ 1 + session + (1 | subject)
   Data: sim_data

REML criterion at convergence: 1639.3

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.6679 -0.4728 -0.0547  0.4959  3.8078 

Random effects:
 Groups   Name        Variance Std.Dev.
 subject  (Intercept) 5402     73.50   
 Residual             2103     45.85   
Number of obs: 150, groups:  subject, 30

Fixed effects:
            Estimate Std. Error t value
(Intercept)  614.455     14.904  41.229
session       -7.529      2.647  -2.844

Correlation of Fixed Effects:
        (Intr)
session -0.355</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sim_data <span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(session, reaction_time, <span class="at">group=</span>subject)) <span class="sc">+</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>subject, <span class="at">ncol=</span><span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">fitted</span>(RI_only)), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span> </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"No pooling: Separate regression for each subject"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Each subject gets their own intercept and slope"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Days of sleep deprivation"</span>, <span class="at">y =</span> <span class="st">"Reaction time (ms)"</span>) <span class="sc">+</span> </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>),<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2025-08-22-effect-of-RIonly_RIRS_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>What does this model assume?</strong></p>
<p>Each subject has their own intercept (baseline reaction time), but they all share the same learning (or fatigue) slope. This is often better than full pooling, because it accounts for subject differences in level — but it may still be too rigid if slopes really do vary. If some participants improve rapidly while others don’t, a fixed slope assumption can:</p>
<ul>
<li>Underestimate uncertainty in the group trend,</li>
<li>Bias the estimate of the average slope,</li>
<li>Lead to false positives (thinking there’s a trend when it’s driven by a few outliers),</li>
<li>Mislead clinical interpretations — e.g.&nbsp;calling someone a “responder” when it’s just model misfit.</li>
</ul>
</section>
<section id="limitations-of-random-intercept-models-in-clinical-inference" class="level2">
<h2 class="anchored" data-anchor-id="limitations-of-random-intercept-models-in-clinical-inference">Limitations of Random Intercept Models in Clinical Inference</h2>
<p>In applied biomedical and clinical research, it is common to assess whether individuals vary in their response to an intervention or over repeated measurements. A random intercept model allows for differences in baseline levels between participants but assumes that all individuals share a common rate of change (i.e., a fixed slope).</p>
<p>This assumption can be problematic. If individuals truly differ in their trajectories—such as some improving and others not—then forcing a single slope across all subjects may misattribute systematic variation to residual noise. This can result in biased fixed-effect estimates and inflated residual variance, especially if a small number of participants deviate substantially from the average trend.</p>
<p>In such cases, interpreting individual deviations from the model as evidence of “responders” or “non-responders” can be misleading. These deviations may reflect model misfit rather than genuine subject-specific effects.</p>
<p>Current consensus in the statistical literature supports the use of random slope models when there is theoretical or empirical justification for individual differences in change over time. These models can account for both baseline heterogeneity and subject-specific trends, offering more accurate and generalizable inference (Gelman &amp; Hill, 2007; Barr et al., 2013).</p>
</section>
<section id="random-slopes" class="level2">
<h2 class="anchored" data-anchor-id="random-slopes">Random slopes:</h2>
<p>To account for individual differences not only in baseline levels but also in rates of change, we now extend the model to include random slopes. This allows each subject to have their own intercept and their own slope with respect to session.</p>
<p>This model is specified as:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>RI_RS_corr <span class="ot">&lt;-</span> lme4<span class="sc">::</span><span class="fu">lmer</span>(reaction_time <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> session <span class="sc">+</span> (session <span class="sc">|</span> subject), sim_data)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(RI_RS_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: reaction_time ~ 1 + session + (session | subject)
   Data: sim_data

REML criterion at convergence: 1550.6

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.06073 -0.52670 -0.00823  0.53737  2.59156 

Random effects:
 Groups   Name        Variance Std.Dev. Corr
 subject  (Intercept) 2090.4   45.72        
          session      565.9   23.79    0.30
 Residual              723.6   26.90        
Number of obs: 150, groups:  subject, 30

Fixed effects:
            Estimate Std. Error t value
(Intercept)  614.455      9.174  66.981
session       -7.529      4.612  -1.632

Correlation of Fixed Effects:
        (Intr)
session 0.147 </code></pre>
</div>
</div>
<p><strong>This model assumes that:</strong></p>
<ul>
<li>The intercepts vary by subject (baseline differences),</li>
<li>The slopes also vary by subject (individual learning rates),</li>
<li>And these random effects can be correlated (e.g., subjects with higher baselines may also learn faster or slower).</li>
</ul>
<p>By allowing for both random intercepts and random slopes, we acknowledge that participants may respond differently over time — something particularly important in biomedical and behavioral research, where inter-individual variability is the norm rather than the exception.</p>
<p>Let’s visualize the fitted lines from this model:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>sim_data<span class="sc">$</span>RI_RS_fitted <span class="ot">&lt;-</span> <span class="fu">predict</span>(RI_RS_corr)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>sim_data <span class="sc">|&gt;</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> session, <span class="at">y =</span> reaction_time, <span class="at">group =</span> subject)) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> subject, <span class="at">ncol =</span> <span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> RI_RS_fitted), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Random intercept and random slope model"</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Each subject has their own intercept and slope"</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Session"</span>, <span class="at">y =</span> <span class="st">"Reaction Time (ms)"</span>) <span class="sc">+</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>), <span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2025-08-22-effect-of-RIonly_RIRS_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Random slope models can:</p>
<ul>
<li>Improve model fit by accounting for structured variability,</li>
<li>Produce more accurate estimates of population-level effects,</li>
<li>Reduce the risk of false positives or negatives due to mis-specified structure,</li>
<li>And provide a framework for investigating individual differences in trajectories — a key concern in many health-related studies.</li>
</ul>
<p>This approach represents what is often called partial pooling: estimates are informed both by the individual subject’s data and by the group-level trend, leading to more stable and interpretable inference, especially in small to moderate samples.</p>
</section>
<section id="comparing-models-do-random-slopes-improve-fit" class="level2">
<h2 class="anchored" data-anchor-id="comparing-models-do-random-slopes-improve-fit">Comparing models: Do random slopes improve fit?</h2>
<p>We now compare two models:</p>
<p>One that allows subjects to differ only in their baseline level (random intercept),</p>
<p>And another that also allows them to differ in their rate of change over sessions (random slope).</p>
<p>Using the Akaike Information Criterion, we can assess model fit:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> <span class="fu">c</span>(<span class="st">"ANOVA"</span>,<span class="st">"mass_regression"</span>,<span class="st">"RI_only"</span>,<span class="st">"RI_RS_corr"</span>),</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC =</span> <span class="fu">c</span>(<span class="fu">AIC</span>(anova_approach),<span class="fu">AIC</span>(no_pooling),<span class="fu">AIC</span>(RI_only),<span class="fu">AIC</span>(RI_RS_corr))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  model             AIC
  &lt;chr&gt;           &lt;dbl&gt;
1 ANOVA           1766.
2 mass_regression 1459.
3 RI_only         1647.
4 RI_RS_corr      1563.</code></pre>
</div>
</div>
<p>Using the REML criterion (restricted maximum likelihood), we can assess model fit:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Model REML criterion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Random intercept only</td>
<td>1639.3</td>
</tr>
<tr class="even">
<td>Random intercept + random slope</td>
<td>1550.6</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Lower AIC values indicate better fit. Here, the random slope model shows a substantially lower AIC, suggesting that accounting for individual variability in slopes improves model fit.</p>
<p>If we wanted to formally test whether adding random slopes improves the model, we could refit both models using maximum likelihood (ML) and then conduct a likelihood ratio test:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>RI_only_ml <span class="ot">&lt;-</span> <span class="fu">lmer</span>(reaction_time <span class="sc">~</span> session <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> subject), sim_data, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>RI_RS_corr_ml <span class="ot">&lt;-</span> <span class="fu">lmer</span>(reaction_time <span class="sc">~</span> session <span class="sc">+</span> (session <span class="sc">|</span> subject), sim_data, <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(RI_only_ml, RI_RS_corr_ml)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Data: sim_data
Models:
RI_only_ml: reaction_time ~ session + (1 | subject)
RI_RS_corr_ml: reaction_time ~ session + (session | subject)
              npar    AIC    BIC  logLik -2*log(L)  Chisq Df Pr(&gt;Chisq)    
RI_only_ml       4 1658.1 1670.2 -825.07    1650.1                         
RI_RS_corr_ml    6 1573.7 1591.8 -780.85    1561.7 88.428  2  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This test examines whether the added complexity (the subject-specific slopes and the correlation between random intercept and random slope) is justified by a significantly better fit.</p>
<p>The model with random slopes:</p>
<ul>
<li>Fits the data substantially better (lower REML),</li>
<li>Produces more conservative fixed-effect estimates (larger SE, smaller t),</li>
<li>Accounts for the correlation between intercepts and slopes across individuals (here: +0.30),</li>
<li>And reduces residual variance (from ~2103 to ~723), indicating that more of the variability is now captured by structured random effects.</li>
</ul>
<p>This supports the idea that in biomedical or behavioral data — where individual responses often differ — a random intercept-only model may be too restrictive and lead to misleading fixed-effect conclusions.</p>
</section>
<section id="interpreting-the-random-effects" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-random-effects">Interpreting the Random Effects</h2>
<p>The random intercept + slope model with added correlation term gives us valuable insight into the structure of variability in our data — not just whether an effect exists on average, but how consistent it is across individuals.</p>
<p>From the model output:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(RI_RS_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: reaction_time ~ 1 + session + (session | subject)
   Data: sim_data

REML criterion at convergence: 1550.6

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-2.06073 -0.52670 -0.00823  0.53737  2.59156 

Random effects:
 Groups   Name        Variance Std.Dev. Corr
 subject  (Intercept) 2090.4   45.72        
          session      565.9   23.79    0.30
 Residual              723.6   26.90        
Number of obs: 150, groups:  subject, 30

Fixed effects:
            Estimate Std. Error t value
(Intercept)  614.455      9.174  66.981
session       -7.529      4.612  -1.632

Correlation of Fixed Effects:
        (Intr)
session 0.147 </code></pre>
</div>
</div>
<ul>
<li><p>Baseline (Intercept) Variability The standard deviation of the intercepts is 45.72 ms, indicating substantial between-subject differences in baseline reaction times. This is expected in behavioral or clinical data, where individuals differ due to prior experience, cognitive ability, or other latent traits.</p></li>
<li><p>Slope (Session Effect) Variability The standard deviation of the random slopes is 23.79 ms, meaning that individuals differ notably in how their reaction times change over sessions — some improve sharply, others remain flat or even worsen slightly. This heterogeneity is clinically relevant and would be obscured by models that assume a common slope.</p></li>
<li><p>Correlation Between Intercepts and Slopes The correlation between intercepts and slopes is +0.30. This suggests a weak-to-moderate tendency for participants with higher baseline reaction times to show steeper improvements (more negative slopes). While not strong, this association may point to individual differences in learning potential — e.g., those starting slower have more room to improve.</p></li>
</ul>
<p>This can be visualized:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>sim_data <span class="sc">|&gt;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">improving =</span> slope_re <span class="sc">&lt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span>reaction_time, <span class="at">x=</span>session, <span class="at">color =</span> improving)) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"TRUE"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"FALSE"</span> <span class="ot">=</span> <span class="st">"gray"</span>)) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> subject, <span class="at">ncol=</span><span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept=</span> <span class="fu">mean</span>(<span class="fu">subset</span>(sim_data,session<span class="sc">==</span><span class="dv">1</span>)<span class="sc">$</span>reaction_time)) <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>),<span class="at">breaks=</span><span class="fu">c</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">4</span>)) <span class="sc">+</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Session"</span>, <span class="at">y =</span> <span class="st">"Reaction Time (ms)"</span>,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="st">"Individual learning trajectories across sessions"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2025-08-22-effect-of-RIonly_RIRS_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Why this matters</em> The comparison to a simpler model (with only random intercepts) showed that assuming a shared slope across participants can lead to misleading fixed-effect estimates. In that model, the session effect was significant:</p>
<p>RI_only: session estimate = -7.53, t = -2.84</p>
<p>But once we allow subject-specific slopes:</p>
<p>RI_RS_corr: session estimate = -7.53, t = -1.63</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Fixed Effect</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RI_only</td>
<td>session</td>
<td>-7.53</td>
<td>2.65</td>
<td>-2.84</td>
</tr>
<tr class="even">
<td>RI_RS_corr</td>
<td>session</td>
<td>-7.53</td>
<td>4.61</td>
<td>-1.63</td>
</tr>
</tbody>
</table>
<p>The estimate is identical in both models, but the standard error increases substantially in the random slope model. This reflects how the RI-only model underestimates uncertainty by ignoring individual variability in slopes. Consequently, the t-value drops from a statistically suggestive level (–2.84) to a more cautious level (–1.63), demonstrating the importance of correctly specifying random effects.</p>
<p>The average effect remains the same, but the uncertainty increases, because the model properly attributes some of the variation to individual differences.</p>
<p>This is exactly what Gelman &amp; Hill (2007) and Barr et al.&nbsp;(2013) argue: failing to include justified random slopes can inflate confidence in fixed effects — potentially leading to spurious conclusions.</p>
</section>
<section id="take-away-message" class="level2">
<h2 class="anchored" data-anchor-id="take-away-message">Take-away message:</h2>
<p>So, what did we learn from all this?</p>
<p>We explored a progression of modeling approaches:</p>
<ul>
<li>From ANOVA-style pooling,</li>
<li>to mass regression (no pooling),</li>
<li>then to partial pooling with a random intercept,</li>
<li>and finally to a model with both random intercepts and slopes, including their correlation.</li>
</ul>
<p>Each step improved the model fit. But here’s the key insight: <strong>Only the model with random slopes gave us a trustworthy picture of individual differences.</strong></p>
<p>The random intercept-only model, while tempting in its simplicity, produced misleading results. Specifically, it underestimated standard errors, leading to inflated Type I error rates. That’s not just a technical detail — it can fundamentally distort scientific conclusions, especially in clinical or psychological studies where understanding who improves and who doesn’t is crucial.</p>
<p>So, if you’re working with repeated measures or hierarchical data and you care about individual variability, responder/non-responder patterns, or generalization, don’t stop at random intercepts.</p>
<p>Modeling the variance-covariance structure of the specific data set (i.e.&nbsp;random terms of the mixed-effect model) aren’t just a technical flourish — they’re essential for honest modeling.</p>
</section>
<section id="old" class="level2">
<h2 class="anchored" data-anchor-id="old">old</h2>
<p>By modeling random slopes:</p>
<p>We acknowledge that people learn differently over time,</p>
<p>We prevent overconfident or misleading group-level inferences,</p>
<p>And we gain access to rich insights about how variability in individual responses relates to baseline ability.</p>
<p>This modeling approach helps move us from averages to individuals, which is crucial in many health, cognitive, and behavioral domains.</p>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section">??</h2>
<ul>
<li>While random intercept models are within the class of linear mixed-effect models, they are often difficult to find use cases for within cognitive neuroscience experiments.</li>
<li>While accounting for individual starting differences is a set up from the ANOVA approach, it still assumes no variability between participants.</li>
<li>Fitting mass linear models (no pooling) overcomes this problem. However, researchers often aim to generalize and make population-based conclusions. It is therefore not optimal for this use case.</li>
<li>Linear mixed-effect models that are modeled appropriately to a specific data set is a great approach (partial-pooling). However, they quickly become tricky to set up when there are multiple predictors, groups, covariates, and especially interactions.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>